[tool.poetry]
name = "fastapi-lab1"
version = "0.1.0"
description = ""
authors = ["Admin <sofiamartyniuk2008@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<4.0"
fastapi = "<0.110.0"
uvicorn = {version = "<0.25.0", extras = ["standard"]}

email-validator = "^2.1.0"
[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
