name: CI/CD Pipeline

on:
  push:
    branches: [ "dev" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          command_timeout: 30m
          script: |
            # 1. Встановлюємо Docker (якщо раптом злетів)
            sudo apt-get update -y
            sudo apt-get install -y docker.io docker-compose-v2
            
            # 2. Налаштування папки
            sudo mkdir -p /home/ubuntu/app
            sudo chown -R ubuntu:ubuntu /home/ubuntu/app
            cd /home/ubuntu/app
            
            # 3. ВИДАЛЯЄМО ВСЕ СТАРЕ (щоб git clone не лаявся)
            rm -rf * .git .github
            
            # 4. Клонуємо проект
            git clone -b dev https://github.com/${{ github.repository }}.git .
            
            # 5. Запуск (використовуємо нову команду docker compose без дефіса)
            sudo docker compose down || true
            sudo docker compose up -d --build